### ISSUE TITLE
(silly but...) Add install instructions / script for newbies

### ISSUE THREAD

**Issue by theiosif** [solidiquis/alacpretty#3]
The best way to gain quick traction on a project that aims to bring more intuitivity, is to keep that intuitivity all the way from the installation to the actual usage. Kudos on the work!

**Comment by solidiquis** [comment]
Will do! My apologies for falling behind on that. Didn't think this would get as much traction as it did but I will get to that tonight :]

**Comment by solidiquis** [comment]
Wrote-up a README! Apologies for the super long delay!
